### ISSUE TITLE
"import these rules into javascript settings" doesn't work

### ISSUE THREAD

**Issue by Owyn** [maximelebreton/quick-javascript-switcher#17]
"import these rules into javascript settings" doesn't work, new entires aren't added, old modified ones - aren't modified, deleted ones - aren't deleted...

**Comment by maximelebreton** [comment]
yes it's not perfect, but it was quickly designed for backing up your rules before the arrival of storage sync.
Now the chrome storage sync is implemented in the extension so i think i'll remove the "import" function.
