### ISSUE TITLE
Not working in incognito mode

### ISSUE THREAD

**Issue by leepowellcouk** [maximelebreton/quick-javascript-switcher#18]
I'm allowing the plugin access to incognito mode, however it doesn't seem to take effect even after multiple page refreshes. Works as expected in non-incognito mode.

Running on Chrome 47.0.2526.73, OS X 10.11.1

**Comment by Arexxk** [comment]
I'm experiencing the same issue. I think it might be related to setting the global JS option to "do not allow any site to run JavaScript". However in incognito, it seems to work if I set Quick JS Switcher to 'on' and reload the page in a different tab instance. I hope this helps.

**Comment by maximelebreton** [comment]
It's a chrome bug, and i'm still waiting for the fix:
https://code.google.com/p/chromium/issues/detail?id=494501

**Comment by maximelebreton** [comment]
Okay i find a (hacky) way to get around the chrome issue, and it now works again in the incognito mode.
https://github.com/maximelebreton/quick-javascript-switcher/blob/master/src/js/core.js#L155
