### ISSUE TITLE
chrome won't load google drive

### ISSUE THREAD

**Issue by micksp** [maximelebreton/quick-javascript-switcher#20]
Hi
If i have this extension enabled, Google chrome won't let me open my google drive page. The page starts loading and then keeps showing the loading indicator, but nothing happens. As soon as i disable this plugin, everything works. Which is a pity because I love this plugin. Could you look into this? 
I use Quick Javascript Switcher 1.4.1 and Chrome Version 50.0.2661.86 (64-bit) on Linux ubuntu (mint rebecca)

Regards
Michael

**Comment by reeddunkle** [comment]
I just discovered and installed this extension yesterday. I'm not having this issue. Can you confirm if it's still happening?

**Comment by micksp** [comment]
@reeddunkle - I don't have this issue anymore. I am on Chrome 60.0.3112.113 on Linux Mint 18.2 (ubuntu 16.04). I honestly can't remember when it was resolved.
