### ISSUE TITLE
"go to javascript settings" broken

### ISSUE THREAD

**Issue by inexist3nce** [maximelebreton/quick-javascript-switcher#28]
material update broke a link, menu item should now point from `chrome://chrome/settings/contentExceptions#javascript` to `chrome://settings/content/javascript`

**Comment by mtimkovich** [comment]
I submitted PR #30 to fix this.

**Comment by maximelebreton** [comment]
This is now fixed on `1.4.4`.
Thanks @mtimkovich fo your help!

Also, if you're interested, I need support for the next release: https://github.com/maximelebreton/quick-javascript-switcher/issues/35
