### ISSUE TITLE
"go to javascript settings" broken

### ISSUE THREAD

**Issue by cirton** [maximelebreton/quick-javascript-switcher#29]
"go to javascript settings" broken。
i can't set default javascript setting.

**Comment by mtimkovich** [comment]
I made a PR for this. #30 

The correct url is chrome://settings/content/javascript

**Comment by ExaFlop1** [comment]
It's still unchanged!

**Comment by maximelebreton** [comment]
This is now fixed on `1.4.4`.

Also, if you're interested, I need support for the next release: https://github.com/maximelebreton/quick-javascript-switcher/issues/35
