### ISSUE TITLE
Please add context menu item to trigger extension?

### ISSUE THREAD

**Issue by mqudsi** [maximelebreton/quick-javascript-switcher#31]
Thanks for this extension, it's almost what I was looking for. On a high-resolution screen, moving the mouse to the icon may require significant travel. It would be nice to have a context menu "disable JavaScript"/"enable JavaScript" option that could be invoked by simply right-clicking anywhere on the page, a la Opera (and others).

**Comment by mtimkovich** [comment]
Hey @mqudsi it looks like this extension might be abandoned. I added a right click toggle option on [my fork](https://github.com/mtimkovich/quick-javascript-switcher2) of this project.

**Comment by maximelebreton** [comment]
Hello @mqudsi and sorry for the late response.
I updated to 1.4.4, and this is now fixed.

Also, if you're interested, I have plans for the next release: https://github.com/maximelebreton/quick-javascript-switcher/issues/35
