### ISSUE TITLE
Add hotkey to toggle JS 

### ISSUE THREAD

**Issue by vt8235** [maximelebreton/quick-javascript-switcher#32]
Please add this feature, would gladly hit keys to disable/enable javascript on the page

**Comment by cirosantilli** [comment]
Related:

- https://github.com/maximelebreton/quick-javascript-switcher/issues/42
- https://github.com/maximelebreton/quick-javascript-switcher/issues/11

**Comment by maximelebreton** [comment]
The shortcut feature has been added in [2013](https://github.com/maximelebreton/quick-javascript-switcher/commit/b5fe0a63dc3c9f47a7052950f8b0169b524fbde5) after this [feature request](https://github.com/maximelebreton/quick-javascript-switcher/issues/11), but not documented so far, so [now it is](https://github.com/maximelebreton/quick-javascript-switcher#shortcut).
