### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by jamiesonbecker** [maximelebreton/quick-javascript-switcher#34]
Another developer states that this is abandoned (https://chrome.google.com/webstore/detail/quick-javascript-switcher/ahjfodbngfpdppljbkhcfhcfdagfgcnj?hl=en-US) and has released a continuation of this plugin.

@maximelebreton Is this project, in fact, abandoned? I find it extremely useful. Thanks!

**Comment by Almenon** [comment]
considering that the last code update was 6 hours ago I think the answer is no

**Comment by maximelebreton** [comment]
@jamiesonbecker No it's not :)

https://github.com/maximelebreton/quick-javascript-switcher/issues/35

@Almenon what responsiveness!

**Comment by jamiesonbecker** [comment]
Closing because the author is alive again :) Welcome back @maximelebreton !
