### ISSUE TITLE
Hotkey Ctrl-w collides with browser default

### ISSUE THREAD

**Issue by mmmmgh** [maximelebreton/quick-javascript-switcher#42]
It is nice to have a JS toggle hotkey. However the current one (ctrl-w) collides with the browser's hotkey for closing the current window which I happen to use regularly.

Therefore: Can we have a configurable hotkey for this extension?

PS: I just discovered your extension and like it very much for its site-specific Javascript handling!

**Comment by cirosantilli** [comment]
Where is that hotkey documented/coded BTW?

**Comment by maximelebreton** [comment]
Hey @cirosantilli, you can find the **default shortcut** in the [manifest.json](https://github.com/maximelebreton/quick-javascript-switcher/blob/master/src/manifest.json#L33), and customize it, but yeah you're right, i've never documented it, so I just updated the [readme](https://github.com/maximelebreton/quick-javascript-switcher), thanks for the report!

**Comment by cirosantilli** [comment]
Nice! Make sure to also show it on the extension page: https://chrome.google.com/webstore/detail/quick-javascript-switcher/geddoclleiomckbhadiaipdggiiccfje Thanks for this Maxim.
