### ISSUE TITLE
plugin is affecting more than just the current site

### ISSUE THREAD

**Issue by ScienceofSpock** [maximelebreton/quick-javascript-switcher#48]
I had this installed on my last machine. I would use it any time a site had aggressive popups or "subscribe now" overlays and such, and it was perfect. I have built a new machine, and this was one of the addons I installed first, but when I get to a site and need to turn off javascript, clicking this turns it off for ALL tabs, not just the current site. Why is it behaving differently now, and how do I get the original behavior back? I do not want to switch off javascript for the entire browser, I want to be able to turn it off PER SITE.

**Comment by maximelebreton** [comment]
Hello @ScienceofSpock, I'm working on a new version, you can access the beta here (no auto-update): https://github.com/maximelebreton/quick-javascript-switcher/issues/47

Please let me know if it solve the problem

**Comment by ScienceofSpock** [comment]
I just tried to install it and got an error: "package is invalid: 'CRX_REQUIRED_PROOF_MISSING'"

**Comment by maximelebreton** [comment]
Are you in developer mode? (top right in extensions page)

**Comment by ScienceofSpock** [comment]
Developer mode is off.

**Comment by maximelebreton** [comment]
I update the readme, follow the second method (.zip): https://github.com/maximelebreton/quick-javascript-switcher/issues/47

**Comment by ScienceofSpock** [comment]
The new one seems to work just fine, thanks.
