### ISSUE TITLE
When I click the icon, the icon display in another window also switches.

### ISSUE THREAD

**Issue by inoue064** [maximelebreton/quick-javascript-switcher#49]
Quick Javascript Switcher 1.4.12
Windows 10
Chrome Portable 84.0.4147.125

1. Open example.com in window A
2. Open example.NET in window B
3. Clicking the icon will switch the icon in another window.
(It is correct that it does not change)

I tried installing v2.0, but maybe it's because Chrome is a little old
It doesn't work when I left-click, and I can't find the menu added by extension in the right-click menu.

**Comment by maximelebreton** [comment]
Hello @inoue064,
this bug is fixed in QJS 2.0, but it's still in beta and I have not yet add the left-click context menu (but i will very soon!),
please use the extension button in the topbar and let me know if you still have the bug.

**Comment by maximelebreton** [comment]
Just added the Right click contextual menu to `QJS 2.0-beta 5`: https://github.com/maximelebreton/quick-javascript-switcher/issues/47
