### ISSUE TITLE
Chrome says extension isn't supported

### ISSUE THREAD

**Issue by ksb86** [maximelebreton/quick-javascript-switcher#71]
Appears to work fine still, just a head up:
<img width="1417" alt="Screenshot 2024-10-15 at 2 10 49 PM" src="https://github.com/user-attachments/assets/56013a59-73bd-4f6b-aafd-5f4233a180dc">

**Comment by ksb86** [comment]
Great extension BTW I use it just about every day

**Comment by maximelebreton** [comment]
Hello @ksb86, i started to work on a v2, based on the manifest v3.
I hope i'll release it soon!
Thanks for reporting!

**Comment by maximelebreton** [comment]
If you want to try the v2, you can download the .zip, extract it and load the folder as unpacked in developer mode in chrome://extensions
https://github.com/maximelebreton/quick-javascript-switcher/archive/refs/heads/2.0.zip

Little doc here: https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world?hl=fr#load-unpacked

**Comment by maximelebreton** [comment]
@ksb86 I just submited the new version to the Chrome Webstore, and waiting for validation.
So the official release will be very soon :)

**Comment by ksb86** [comment]
> If you want to try the v2, you can download the .zip, extract it and load the folder as unpacked in developer mode in chrome://extensions https://github.com/maximelebreton/quick-javascript-switcher/archive/refs/heads/2.0.zip
> 
> Little doc here: https://developer.chrome.com/docs/extensions/get-started/tutorial/hello-world?hl=fr#load-unpacked

Hmm, I tried this but got an error about a missing manifest file.  I tried moving the manifest.js file up a directory from `src` to `quick-javascript-switcher-2.0` but still no luck. Not sure what that is about. 
<img width="554" alt="Screenshot 2024-10-16 at 3 27 01 PM" src="https://github.com/user-attachments/assets/94da3110-23de-44f4-bf56-8069a93e68c1">

**Comment by maximelebreton** [comment]
The v2 is out on Chrome webstore :)
https://chromewebstore.google.com/detail/quick-javascript-switcher/geddoclleiomckbhadiaipdggiiccfje
