### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by anatoliy-savchak** [maximelebreton/quick-javascript-switcher#76]
Previous version worked almost perfect. New version does not work at all. Clicking on the new "pill" button does not do a thing.

**Comment by maximelebreton** [comment]
Hello @anatoliy-savchak, and thanks for your report.
I just released a `2.2.0` version to the Chrome Webstore and it should fix the problem.

Can you confirm it?

**Comment by anatoliy-savchak** [comment]
Sort of works. 

But I need to refresh page nevertheless, after which I see impact. In earlier version it refreshed automatically. Also icon stays the same so unclear if it on or off.

**Comment by samuelkadolph** [comment]
Seconded. Icon does not change to reflect JS status nor does the page refresh.

**Comment by maximelebreton** [comment]
Argh.

@anatoliy-savchak & @samuelkadolph

**First step:**
Could you send me a screenshot of these pages:
QJS options: chrome://extensions/?options=geddoclleiomckbhadiaipdggiiccfje
Chrome Javscript content settings: chrome://settings/content/javascript

This gonna help me to understand whats going on.

**Second step:**
Can you try to uninstall and reinstall it.

Do you have other chrome extensions that disable javascript?

Thanks for your help.

**Comment by anatoliy-savchak** [comment]
Disabling all other chrome extensions had no effect.

But **reinstall** did the trick. No idea why, quite surprising.
Thanks!

**Comment by samuelkadolph** [comment]
Same. Reinstalling fixed it.
